# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpectationSneakers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExpectationSneakers

  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true

  target 'ExpectationSneakersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExpectationSneakersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
